# MIT-Schemeのrlwrap対応
if check-command scheme; then
  if check-command rlwrap; then
    alias scheme='rlwrap -r -c -f "$HOME/.scheme_completion.txt" scheme'
  else
    warn "you should install rlwrap."
  fi
fi

alias ..='cd ../'
alias ...='cd ../../'

# Emacs
alias e='emacsclient -n -c '
alias t='emacsclient -nw -c '
alias estart='emacs --daemon'
alias ekill="emacsclient -e '(kill-emacs)'"

