set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set showcmd
set laststatus=2
set wildmode=list:longest
set clipboard&
set clipboard^=unnamedplus

" visual
set number
set cursorline
set showmatch
set virtualedit=onemore
set visualbell

" cursor move
nnoremap j gj
nnoremap k gk
syntax enable

" space/tab
set autoindent
set smartindent
set list listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set expandtab
set shiftwidth=4
set tabstop=4

" search
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch
nmap <Esc><Esc> :nohlsearch<CR><Esc>

" shebang
autocmd BufWritePost * :call AddExecmod()
function AddExecmod()
    let line = getline(1)
    if strpart(line, 0, 2) == "#!"
        call system("chmod +x ". expand("%"))
    endif
endfunction

" dein
let $CACHE = expand('~/.cache')
if !isdirectory($CACHE)
  call mkdir($CACHE, 'p')
endif
j
let s:dein_base = $CACHE .. '/dein/'
let s:dein_dir = s:dein_base .. 'repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
  endif
  execute 'set runtimepath^=' .. substitute(
        \ fnamemodify(s:dein_dir, ':p') , '[/\\]$', '', '')
endif

call dein#begin($CACHE)
call dein#add(s:dein_dir)
call dein#add('vim-scripts/molokai')
call dein#end()

if dein#check_install()
    call dein#install()
endif

colorscheme molokai

