# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="muse"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(sudo zsh-autosuggestions zsh-syntax-highlighting git git-prompt asdf docker kubectl aws zsh-interactive-cd minikube)

case ${OSTYPE} in
darwin*)
    plugins=(macos $plugins)
    ;;
linux*)
    ;;
esac

fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#PROMPT='$(git_prompt_short_sha)'
#RPROMPT='[%*]'

# Ctrl+u
bindkey \^U backward-kill-line

if [ -f ~/.sh_aliases ]; then
    . ~/.sh_aliases
fi

for f in $(find "$HOME/.shell.d/" -type f -name \*.sh -or -name \*.zsh); do
  if [ -f $f ]; then
      . $f
  fi
done

# af-magic.zsh-theme
#
# Author: Andy Fleming
# URL: http://andyfleming.com/

prompt_color="%F{250}"
curdir_color="%F{034}"
secondary_color="%F{240}"

# dashed separator size
export VIRTUAL_ENV_DISABLE_PROMPT=1

function show_statusline {
  local code="%(?.%F{green}.%F{red}%B)$?%b"
  local hhmmss="$(date +"%H:%M:%S")"
  local pyenv_dir="${VIRTUAL_ENV:-$CONDA_DEFAULT_ENV}"
  local pyenv="${python_env_dir##*/}"

  local elements=("$code" "$hhmmss")
  if [[ -n "$pyenv" ]]; then
      elements+=("venv:$pyenv")
  fi

  for i in {1..$#elements}; do
      elements[$i]="${secondary_color}[${elements[$i]}${secondary_color}]"
  done

  local info="${(j:-:)elements}"
  local info_length=$(echo $info | sed -E 's/%([bfB]|F\{[^\}]+?\}|\([^\)]+?\))//g' | wc -c)
  local rmargin=$(( COLUMNS - info_length ))

  echo "${info}${(l.rmargin..-.)}%f"
}

# primary prompt: dashed separator, directory and vcs info
PROMPT="\$(show_statusline)
${curdir_color}%B%~%f%b \$(git_super_status)${prompt_color}%(!.#.$) %f"
PROMPT2="${prompt_color}> %f"

RPROMPT="${secondary_color}%B%n@%m%b%f"

# git settings
#ZSH_THEME_GIT_PROMPT_PREFIX=" ${FG[075]}(${FG[078]}"
#ZSH_THEME_GIT_PROMPT_CLEAN=""
#ZSH_THEME_GIT_PROMPT_DIRTY="${FG[214]}*%{$reset_color%}"
#ZSH_THEME_GIT_PROMPT_SUFFIX="${FG[075]})%{$reset_color%}"

# git prompt
ZSH_THEME_GIT_PROMPT_PREFIX="%f%b("
ZSH_THEME_GIT_PROMPT_SUFFIX=")"
ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
ZSH_THEME_GIT_PROMPT_BRANCH="%B%F{063}"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%F{124}!"
ZSH_THEME_GIT_PROMPT_CHANGED="%F{214}*"
ZSH_THEME_GIT_PROMPT_DELETED="%F{096}-"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%F{009}?"
ZSH_THEME_GIT_PROMPT_STAGED="%F{010}+"
ZSH_THEME_GIT_PROMPT_STASHED="%F{027}.."
ZSH_THEME_GIT_PROMPT_BEHIND="<"
ZSH_THEME_GIT_PROMPT_AHEAD=">"
ZSH_THEME_GIT_PROMPT_CLEAN="%F{046}="
